global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.0.2.4:9090']

  - job_name: 'glances'
    static_configs:
      - targets: ['glances:61208']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
